rootProject.name = "HealthcareResearchKit"
include(":samples:researchsample")
include(":kit")
include(":healthdata-link:interface")
include(":backend-integration:interface")
include(":backend-integration:healthstack-adapter")
include(":healthdata-link:healthplatform")
include(":healthdata-link:healthconnect")
include(":resources:korean")
include(":app-support")
